# Generated by Django 2.0.6 on 2018-06-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_vue_todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user_id',
            new_name='user',
        ),
    ]
